Added localhost to accepted TLDs
benjie/mehserve pull request #32
Opened 2021-11-15 17:42 UTC by lake-effect

This allows the common TLD for 127.0.0.1 to be used with mehserve as
well (see https://en.wikipedia.org/wiki/.localhost).

I'm still working on this but I wanted to propose the idea for discussion.

2021-11-15 18:15 UTC, benjie commented
Sounds good to me. What OS are you on?

2021-11-15 18:25 UTC, lake-effect commented
I'm on Ubuntu LTS, but I'll be testing this with workmates on OSX.

2021-11-15 18:30 UTC, benjie commented
Fantastic. I was wondering if it'll need a resolver installed for OSX or not (like we have for the other two domains).

2021-11-15 21:34 UTC, remindmmeinzer commented
Can you clarify what you mean by resolver?

I'm working on troubleshooting getting this change working on OSX

2021-11-15 21:36 UTC, remindmmeinzer commented
Just realized what you meant. `sudo cp /etc/resolver/meh /etc/resolver/localhost` got it working as expected!

2021-11-16 17:39 UTC, benjie requested changes
Looking good! You may need to rerun prettier after accepting the backtick tweak.

2021-11-16 17:39 UTC, benjie commented on README.md
> +This'll tell mehserve to proxy all HTTP requests for `mysite.meh, mysite.localhost`,
```suggestion
This'll tell mehserve to proxy all HTTP requests for `mysite.meh`, `mysite.localhost`,
```

2021-11-16 17:39 UTC, benjie commented on src/ssl.js
> +DNS.2 = ${hostname}.localhost
Please add to the end with `DNS.4 =`; we don't want conflicting numbers :+1:

2021-11-24 10:33 UTC, benjie requested changes

2021-11-24 10:33 UTC, benjie commented on README.md
> +This'll tell mehserve to proxy all HTTP requests for `mysite.meh`, mysite.localhost`,
```suggestion
This'll tell mehserve to proxy all HTTP requests for `mysite.meh`, `mysite.localhost`,
```

2021-11-24 10:33 UTC, benjie commented on README.md
> +requesting `http://staticsite.meh/`and `http://mysite.localhost`
```suggestion
requesting `http://staticsite.meh/` or `http://mysite.localhost`
```

2021-11-24 10:34 UTC, benjie approved these changes
LGTM :+1:

2021-11-24 14:34 UTC, merged

2021-11-24 14:38 UTC, benjie commented
2.1.0 released :tada: